# Generated by Django 5.0.6 on 2024-06-08 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 8, 13, 41, 56, 414004, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='MessageToTeacher',
        ),
    ]
