# Generated by Django 5.0.6 on 2024-06-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_classassignment_end_date_delete_messagetoteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
