# Generated by Django 5.0.6 on 2024-06-10 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0013_remove_studentmarks_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 16, 10, 57, 330709, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
