# Generated by Django 5.0.6 on 2024-06-10 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0014_studentmarks_id_alter_classassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 16, 12, 40, 809232, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='studentmarks',
            unique_together={('semester', 'student')},
        ),
    ]
