# Generated by Django 5.0.6 on 2024-06-10 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0016_alter_studentmarks_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 16, 13, 59, 644504, tzinfo=datetime.timezone.utc)),
        ),
    ]
