# Generated by Django 5.0.6 on 2024-06-10 17:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0026_studentmarks_semester_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('Semester', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 17, 14, 22, 574269, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.semester'),
        ),
    ]
