# Generated by Django 5.0.6 on 2024-06-10 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0027_semester_alter_classassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 17, 23, 43, 819935, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='Semester',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
