# Generated by Django 5.0.6 on 2024-06-10 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0028_alter_classassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 17, 25, 6, 637187, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='semester',
            name='Semester',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
