# Generated by Django 5.0.6 on 2024-06-10 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0029_alter_classassignment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='Semester',
            new_name='Semester_id',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='semester',
            new_name='semester_id',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 17, 27, 45, 372743, tzinfo=datetime.timezone.utc)),
        ),
    ]
