# Generated by Django 5.0.6 on 2024-06-10 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0031_alter_studentmarks_semester_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='semester_id',
            new_name='semester',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 10, 17, 36, 39, 391810, tzinfo=datetime.timezone.utc)),
        ),
    ]
