# Generated by Django 5.0.6 on 2024-06-11 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0040_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 4, 51, 24, 127886, tzinfo=datetime.timezone.utc)),
        ),
    ]
