# Generated by Django 5.0.6 on 2024-06-11 14:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0043_alter_classassignment_end_date_delete_vivamarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 14, 8, 11, 881899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='VivaMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('maximum_mark', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viva_marks', to='classroom.student')),
            ],
        ),
    ]
