# Generated by Django 5.0.6 on 2024-06-11 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0046_remove_studentmarks_viva_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 14, 40, 10, 314736, tzinfo=datetime.timezone.utc)),
        ),
    ]
