# Generated by Django 5.0.6 on 2024-06-11 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0049_studentmarks_viva_marks_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='viva_marks_obtained',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 14, 53, 9, 661958, tzinfo=datetime.timezone.utc)),
        ),
    ]
