# Generated by Django 5.0.6 on 2024-06-11 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0050_remove_studentmarks_viva_marks_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 11, 15, 56, 2, 947963, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='maximum_marks',
            field=models.IntegerField(default=16),
        ),
    ]
