# Generated by Django 5.0.6 on 2024-06-13 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0051_alter_classassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='assignment_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='viva_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 13, 6, 9, 12, 963383, tzinfo=datetime.timezone.utc)),
        ),
    ]
