# Generated by Django 5.0.6 on 2024-06-14 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0057_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 9, 55, 44, 840167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='assignment_marks',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='viva_marks',
            field=models.FloatField(blank=True, null=True, unique=True),
        ),
    ]
