# Generated by Django 5.0.6 on 2024-06-14 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0067_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='marks_obtained_viva',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 10, 44, 32, 364424, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
