# Generated by Django 5.0.6 on 2024-06-14 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0068_studentmarks_marks_obtained_viva_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='marks_obtained_viva',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='viva_marks',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 11, 9, 8, 564184, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks_obtained',
            field=models.IntegerField(),
        ),
    ]
