# Generated by Django 5.0.6 on 2024-06-14 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0069_remove_studentmarks_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 14, 11, 14, 45, 55068, tzinfo=datetime.timezone.utc)),
        ),
    ]
