# Generated by Django 5.0.6 on 2024-06-16 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0070_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='assignment_marks',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='viva_marks',
            field=models.FloatField(default=2.5),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 10, 31, 31, 160036, tzinfo=datetime.timezone.utc)),
        ),
    ]
