# Generated by Django 5.0.6 on 2024-06-16 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0071_studentmarks_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 10, 35, 49, 689871, tzinfo=datetime.timezone.utc)),
        ),
    ]
