# Generated by Django 5.0.6 on 2024-06-16 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0072_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 10, 53, 55, 747135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='assignment_marks',
            field=models.FloatField(default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks_obtained',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='viva_marks',
            field=models.FloatField(default=2.5, null=True),
        ),
    ]
