# Generated by Django 5.0.6 on 2024-06-16 11:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0074_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 16, 11, 42, 15, 968558, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='AssignmentVivaMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('subject_name', models.CharField(max_length=250)),
                ('assignment_mark_obtained', models.FloatField(default=2.5, null=True)),
                ('viva_mark_obtained', models.FloatField(default=2.5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_student_marks', to='classroom.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_student_marks', to='classroom.teacher')),
            ],
        ),
    ]
