# Generated by Django 5.0.6 on 2024-06-20 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0075_alter_classassignment_end_date_assignmentvivamarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentvivamarks',
            name='assignment_mark_obtained',
            field=models.FloatField(blank=True, default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentvivamarks',
            name='viva_mark_obtained',
            field=models.FloatField(blank=True, default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 20, 17, 25, 44, 695151, tzinfo=datetime.timezone.utc)),
        ),
    ]
