# Generated by Django 5.0.6 on 2024-06-22 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0076_alter_assignmentvivamarks_assignment_mark_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 6, 24, 46, 636708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='assignment_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='marks_obtained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentmarks',
            name='viva_marks',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
