# Generated by Django 5.0.6 on 2024-06-22 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0077_alter_classassignment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentvivamarks',
            name='assignment_mark_obtained',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='assignmentvivamarks',
            name='viva_mark_obtained',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 6, 46, 58, 453961, tzinfo=datetime.timezone.utc)),
        ),
    ]
