# Generated by Django 5.0.6 on 2024-06-22 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0078_alter_assignmentvivamarks_assignment_mark_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='assignment_marks',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='viva_marks',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 6, 48, 19, 734143, tzinfo=datetime.timezone.utc)),
        ),
    ]
