# Generated by Django 5.0.6 on 2024-06-22 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0079_remove_studentmarks_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='assignment_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='viva_marks',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 7, 3, 57, 160705, tzinfo=datetime.timezone.utc)),
        ),
    ]
