# Generated by Django 5.0.6 on 2024-06-22 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0080_studentmarks_assignment_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentvivamarks',
            name='assignment_mark_obtained',
            field=models.FloatField(default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='assignmentvivamarks',
            name='viva_mark_obtained',
            field=models.FloatField(default=2.5, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 7, 5, 40, 846759, tzinfo=datetime.timezone.utc)),
        ),
    ]
