# Generated by Django 5.0.6 on 2024-06-22 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0081_alter_assignmentvivamarks_assignment_mark_obtained_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmarks',
            old_name='assignment_marks',
            new_name='assignment_mark_obtained',
        ),
        migrations.RenameField(
            model_name='studentmarks',
            old_name='viva_marks',
            new_name='viva_mark_obtained',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 7, 23, 14, 492763, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='AssignmentVivaMarks',
        ),
    ]
