# Generated by Django 5.0.6 on 2024-06-22 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0082_rename_assignment_marks_studentmarks_assignment_mark_obtained_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 7, 52, 12, 364606, tzinfo=datetime.timezone.utc)),
        ),
    ]
