# Generated by Django 5.0.6 on 2024-06-22 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0083_alter_classassignment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='marks_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Viva', 'Viva')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 13, 40, 54, 599364, tzinfo=datetime.timezone.utc)),
        ),
    ]
