# Generated by Django 5.0.6 on 2024-06-22 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0084_studentmarks_marks_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='marks_type',
        ),
        migrations.AlterField(
            model_name='classassignment',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 22, 13, 44, 56, 977359, tzinfo=datetime.timezone.utc)),
        ),
    ]
